### ISSUE TITLE
Use `fire` to do the CLI and `rich` to replace `tqdm`

### ISSUE THREAD

**Issue by sayakpaul** [rishiraj/fastrequests#1]
Excellent stuff!

Two suggestions as the title say. I can work on these if you want. 

Also, should there be a disclaimer if people want to download something from the Hugging Face Hub, they're likely better off using `hf_transfer`?

**Comment by rishiraj** [comment]
Thanks a lot for the recommendations @sayakpaul 

`fire` just makes CLI so much simpler. I have integrated it. Also added the warning for `hf_transfer`

However I’m not very familiar with `rich`. It would really be helpful if you can look into this.

**Comment by sayakpaul** [comment]
Ah beautiful. Regarding `rich`, in retrospect, I now think it's better off with `tqdm` as it is currently.
